backend = "glx";  
use-damage = true;
glx-no-stencil = true;
animations = true;
unredir-if-possible = false;
fading = true;
fade-in-step = 0.1;
fade-out-step = 0.1;
fade-delta = 8;
no-fading-openclose = false;
animation-stiffness = 250.0;
animation-clamping = true;
animation-for-open-window = "maximize";
animation-for-unmap-window = "minimize";
animation-for-transient-windows = "zoom";
shadow = false;
vsync = true;
xrender-sync-fence = true;
blur: {
	method = "dual_kawase";
	strength = 2;
	background = true;
	background-frame = true;
	background-fixed = false;
}



opacity-rule = [
	"90:focused",
	"85:!focused",
];


