background #0b0b0c
foreground #616269

cursor #d9dadf
cursor_shape block
cursor_blink_interval 0.5

selection_background #3f2c5a
selection_foreground #d9dadf

color0 #0b0b0c
color1 #8c0d1a
color2 #5d625e
color3 #8c7c5a
color4 #2c3a5a
color5 #3f2c5a
color6 #485a63
color7 #d9dadf
color8 #c1c2c4
color9 #a81423
color10 #7b827d
color11 #a6946c
color12 #394b75
color13 #553b78
color14 #627985
color15 #f0f1f5

font_family SourceCodePro
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

window_pedding_width 10 10 10 10

scrollback_lines 10000

enable_audio_bell no

tab_bar_edge top
tab_bar_style powerline
tap_powerline_style slanted

enabled_layouts splits:split_axis=horizontal

copy_on_select yes
strip_trailing_spaces smart
confirm_on_windows_close 0
#background_image ~/wallpapers/kitty.jpg
#background_image_layout mirror-tiled
background_tinit 0.7
