background #171529
foreground #c5b9ff

cursor #fef65b
cursor_shape block
cursor_blink_interval 0.5

selection_background #3a2c4d
selection_foreground #ff7ed8

color0 #171529
color1 #79ffc4
color2 #00ffff
color3 #973DAD
color4 #5B51AC
color5 #ff7ed8
color6 #482da2
color7 #fef65b
color8 #695bd7
color9 #79ffc4
color10 #00ffff
color11 #ff7ed8
color12 #5b51ac
color13 #695BD7
color14 #ff7ed8
color15 #695db7

font_family SourceCodePro
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

window_pedding_width 10 10 10 10

scrollback_lines 10000

enable_audio_bell no

tab_bar_edge top
tab_bar_style powerline
tap_powerline_style slanted

enabled_layouts splits:split_axis=horizontal

copy_on_select yes
strip_trailing_spaces smart
confirm_on_windows_close 0
#background_image ~/wallpapers/kitty.jpg
#background_image_layout mirror-tiled
background_tinit 0.7
