#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width	2
bspc config window_gap 		6

bspc config split_ratio 	0.52
bspc borderless_monocle 	true
bspc config gapless_mode 	true

bspc rule -a Screenkey manage=off


bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

# Цвета в формате #RRGGBB
#bspc config normal_border_color "#482da2"     # Обычное окно (цвет панели инструментов)
#bspc config active_border_color "#79ffc4"     # Активное окно (неоново-бирюзовый текст)
#synth84
#bspc config focused_border_color "#ff7ed8"    # Сфокусированное окно (розовый)
#bspc config presel_border_color "#973DAD"     # Предварительный выбор 

#bspc config normal_border_color "#000000" gothic
#bspc config active_border_color "#616269" gothic

bspc config normal_border_color "#81a1c1"
bspc config focused_border_color "#d8dee9"


setxkbmap -layout us,ru -option grp:alt_shift_toggle
